spring.application.name=lgds_backend
spring.datasource.url=jdbc:postgresql://dpg-d83h6567r5hc73bq53ig-a.oregon-postgres.render.com/lgds_krd2

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=lgds_krd2_user
#spring.datasource.username=postgres
spring.datasource.password=cK4Sp8H3upFLJdJRo9wE2zUvU2c7Yw6O
#spring.datasource.password=ALUNO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/back-end-lgds/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true